name: farawayclothing
on:
  schedule:
    - cron:  '0 0 * * 3,5'
env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}
jobs:
  kadin_job:
    uses: ./.github/workflows/reusable.yml
    with:
      GENDER: sponsor
      maxconcurrency: '5'
      WEBSITE: 'biraradamoda'
      marka: 'farawayclothing'
    secrets: inherit
